#!/usr/bin/env ruby
site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'gsettings',
	:path => 'src/cookbooks/gsettings'
cookbook 'system',
	:path => 'src/cookbooks/system'
cookbook 'user',
	:path => 'src/cookbooks/user'
cookbook 'nodejs', '~> 2.4.0'
